#! /bin/bash 

### BEGIN INIT INFO
# Provides:          recSaveGPSAtBoot
# Required-start:    $all
# Required-stop:     $all
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6  
# Short-Description: 
# Description: 
### END INIT INFO 
#sleep 20

gpsWavesDir=/home/pi/microSWIFT/GPSwaves
case "$1" in 
	start)
		echo "Starting to record and send gps data"
		cd $gpsWavesDir
#		./runRecordSendGPS
		;;
	stop)
		echo "stopping recording and sending gps data"
		killall recSaveGPSAtBoot
		;;
	*)
		echo "Usage: /etc/init.d/recSaveGPSAtBoot start|stop" 
		;;
esac 
