#! /bin/bash 

### BEGIN INIT INFO
# Provides:          recVoltAtBoot
# Required-start:    $all
# Required-stop:     $all
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6  
# Short-Description: 
# Description: 
### END INIT INFO 
sleep 20

voltDir=/home/pi/microSWIFT/sensors
case "$1" in
	start)
		echo "Starting to record voltage data"
		cd $voltDir
		./runRecVolt
		;;
	stop)
		echo "stopping recording voltage data"
		killall recVoltAtBoot
		;;
	*)
		echo "Usage: /etc/init.d/recVoltAtBoot start|stop" 
		;;
esac
